### PR TITLE
feat(auth): adding userpass and ldap auth

### PR DESCRIPTION
**Pull request by saipranav**
PR helps in appending /{username} at last after /login in path while calling vault auth API.

Related and fixes https://github.com/hashicorp/vault-action/issues/433

Added approle test which can now run as part of not just in basic integration suite instead of enterprise alone

Please review and let me know if I need to code it differently since I am not super familiar with nodejs.

Let me know If you need me to add changelog, it had pull request ids so thought you might add at later stage

### CODE REVIEW

**Review by robmonte — COMMENTED** [review]
Thanks so much for this contribution! I've been testing this out myself and everything seems to work well.

I left review comments on the code and also have a couple callouts below:

The `action.yml` file also needs to be updated to list the new inputs for username and password. Here's my recommended descriptions to start with, and I can ask others on my team to provide feedback on them:
* Username: 'The username of the user to log in to Vault as. Available to both Userpass and LDAP auth methods'
* Password: 'The password of the user to log in to Vault as. Available to both Userpass and LDAP auth methods'

&nbsp;

What prompted these changes to `index.js`? I'll have to ask someone to help review these changes; I simply don't have enough JS experience for that one.

**Comment by saipranav** [comment]
Thanks for the review.

I forgot the action.yml part, added it now. 

I removed changes for the index.js inside dist/ after seeing this comment in recent pull request https://github.com/hashicorp/vault-action/pull/208#pullrequestreview-650402798

**Review by robmonte — APPROVED** [review]
Nice find about the `index.js` changes. Everything seems great. I'm just asking for a quick second opinion on the description text before merging 👍

**Comment by saipranav** [comment]
Thanks, Robert.

**Comment by robmonte** [comment]
Hi @sladebaumann - Sorry about the wait time, but I wanted to let you know that v2.6.0 went out today with this feature 😄

**Pull request merged**
