### PR TITLE
chore(readme): adding readme for #440

### PR DESCRIPTION
**Pull request by saipranav**
I forgot to commit the readme.

https://github.com/hashicorp/vault-action/pull/440

### CODE REVIEW

**Comment by saipranav** [comment]
@robmonte for quick review

**Review by maxcoulombe — APPROVED** [review]
Thanks for coming back to this to add documentation for others, this is highly appreciated.

Everything looks good on my side!

**Comment by saipranav** [comment]
Thanks @maxcoulombe
Any idea when we can see this PR changes as a release.

**Comment by robmonte** [comment]
Thanks for following up with this, I apologize that I somehow missed this after originally merging the feature PR. I believe the release will be within a few more weeks at most.

**Comment by robmonte** [comment]
@saipranav Wanted to let you know that v2.6.0 is released with the feature now. Sorry about the wait!

**Comment by saipranav** [comment]
Thanks for letting me know.

**Pull request merged**
