### PR TITLE
fix(secrets): allow dynamic secrets to be read

### LINKED ISSUE #396: [FEAT] Support reading temporary database credentials
**Is your feature request related to a problem? Please describe.**
If I understand correctly, this action is limited to KV stores and requires one to specific not only a path but also key to retrieve. 
For the [database secret engine](https://developer.hashicorp.com/vault/docs/secrets/databases) this creates a problem - here one would want to make a single request against Vault and return both the username and password not just either of them. 

It would be great if this action would support extracting all keys of a secret as json when providing `*` as a selector

**Describe the solution you'd like**
```yaml
secrets: |
  postgres/creds/foo * | DB_CREDS;
```
Results in the following json string to be stored in `DB_CREDS`: `{"username": "some-temp-username", "password": "some-temp-password"}`

**Current result**
selector gets wrapped into `data."*"` which doesn't work.

**Describe alternatives you've considered**
Writing my own raw get request to Vault

### PR DESCRIPTION
**Pull request by ibacalu**
This would allow reading of `data.*` thus accessing all dynamic secret properties.
Resolves #396

### CODE REVIEW

**Comment by bimtauer** [comment]
Anyone here willing to review this? 🙏🏼

**Comment by maxcoulombe** [comment]
Hi, would you say [this review](https://github.com/hashicorp/vault-action/pull/238) accomplishes the same objective of allowing users to read all properties of a secret at once?

If yes, I think it'd be preferable to focus on #238 as I find the added functionality of being able to optionally add a prefix useful to avoid collisions and group related secret properties.

**Comment by ibacalu** [comment]
@maxcoulombe I haven't tested out #238. It could work as well although the actual use case might be different.
This PR would allow us to get dynamic secrets from Vault.
This would be an example:
```yaml
secrets: |
          postgres/creds/dbname * | DB_CRED;
```
The trick with dynamic secrets is that you can only make 1 request. Every additional request is going to generate different values.
If #238 can do the same with 1 request only, and stores the keys with a prefix, then yes, let's go for that.
Anything that would unblock this thing.

**Comment by fairclothjm** [comment]
Closing as this should be fixed by https://github.com/hashicorp/vault-action/pull/488.

Please feel free to reopen if you feel this was a mistake, or if there is additional information to add. Thanks!

**Pull request closed without merging**
