### PR TITLE
Freeze node/npm version to work around package-lock bug

### PR DESCRIPTION
**Pull request by swenson**
Bug is here: https://github.com/npm/cli/issues/4660

Tests passed here: https://github.com/hashicorp/vault-action/runs/6908644514

### CODE REVIEW

**Comment by calvn** [comment]
Looks like `npm install` is still failing

**Comment by swenson** [comment]
@calvn I think it is due to `semantic-release`. Working on it.

**Comment by swenson** [comment]
Okay, this should be good now. Tests will fail here though for some reason.

**Review by calvn — APPROVED** [review]

**Comment by swenson** [comment]
Thanks!

**Pull request merged**
