### PR TITLE
feat(): make secrets parameter optional

### LINKED ISSUE #289: [FEAT] Make `secrets` parameter optional so we can use this action just to get the token.
**Is your feature request related to a problem? Please describe.**
The `secrets` parameter should not be mandatory. There is the option for `exportToken`, which is what I want to use to configure the Vault Terraform provider. However, with `secrets` being mandatory, it requires me to read a secret that I do not need. 

**Describe the solution you'd like**
The `secrets` parameter to not be mandatory, and allow us to use this action to simply get a Vault token to pass into other tooling.  

**Describe alternatives you've considered**
Honestly, none. Just grabbing a secret for the sake of using this action? I suppose I could create my own action that simply gets the token itself and posts to the login endpoint, but why not just use this one when it does the job?

**Additional context**
I am evaluating this action to use JWT with Github OIDC, as a potential replacement for internal automation around Vault access from CI. When configuring the Terraform Vault provider, you minimally need an endpoint, a token and, in our case, a namespace. I just want that sweet, sweet token. I don't wish to pass secrets into Terraform directly for example. It seems unnecessary to read a secret just to use this action to get a token.

### PR DESCRIPTION
**Pull request by kevinschoonover**
closes #289 

tested this PR locally using [act](https://github.com/nektos/act)

### CODE REVIEW

**Review by kdomanski — APPROVED** [review]

**Review by tcraxs — APPROVED** [review]

**Comment by TomNorth** [comment]
Will this get merged soon? If not I need to create my own action in the next couple of days, but I'd rather avoid it!

(Thanks for this)

**Comment by kevinschoonover** [comment]
I need a hashicorp maintainer to approve before it can be merged.

@tvoran do you have any cycles to take a look / is there any interest in this change?

**Review by tomhjp — COMMENTED** [review]
Thanks for opening this. LGTM, although I'm not keen on maintaining yarn.lock alongside package-lock.json unless we get some infrastructure around keeping them in sync (e.g. some kind of CI to ensure `yarn import` gives a consistent result?). Could you delete it for now please?

**Comment by kevinschoonover** [comment]
Sorry about that! Should be done now.

**Review by tomhjp — APPROVED** [review]
Thank you!

**Pull request merged**
